name: eng_dictionary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.13.0
  window_size: ^0.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  dotenv: ^4.2.0
  json_serializable: ^6.7.1
  crypto: ^3.0.3
  shelf_cors_headers: ^0.1.5
  jwt_decoder: ^2.0.1
  mysql_client: ^0.0.27 # hoặc phiên bản mới nhất
  mysql1: ^0.20.0
  path: ^1.9.1
  http: ^1.3.0
  dart_jsonwebtoken: ^3.2.0
  sqlite3: ^2.1.0  # Thêm dòng này
  sqlite3_flutter_libs: ^0.5.0
  file_selector: ^1.0.0
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.2
  shared_preferences: ^2.2.2 # (hoặc phiên bản mới nhất)
  image_picker: ^0.8.6  # Dùng để chọn ảnh từ gallery
  path_provider: ^2.0.11  # Dùng để lấy đường dẫn lưu file
  device_info_plus: ^9.0.3  # Dùng để lấy thông tin thiết bị
  pin_code_fields: ^8.0.0
  html: ^0.15.4
  intl: ^0.18.1
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  server: server

flutter:
  uses-material-design: true
  assets:
    - assets/vocabulary.json