name: eng_dictionary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  shelf: ^1.4.0            # Framework xử lý HTTP
  shelf_router: ^1.1.4     # Định tuyến API
  mysql1: ^0.20.0          # Kết nối MySQL (hoặc sqlite3 nếu dùng SQLite)
  dotenv: ^4.2.0           # Đọc biến môi trường
  json_serializable: ^6.7.1  # Hỗ trợ JSON

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
